spring.application.name=do_an

spring.datasource.url=jdbc:mysql://localhost:3306/health_tracker
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.ai.google.genai.api-key=AIzaSyCItHy_5NgjeW7IEkckccFizjEVk1oZvA4
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Cấu hình để custom lỗi 404 (Không tìm thấy đường dẫn API)
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false