spring.application.name=ai
server.port=8087

spring.ai.model.chat=openai
spring.ai.openai.api-key=${GROQ_API_KEY:}
spring.ai.openai.base-url=${AI_BASE_URL:https://api.groq.com/openai}
spring.ai.openai.chat.options.model=${AI_MODEL:llama-3.1-8b-instant}
spring.ai.openai.chat.options.temperature=${AI_TEMPERATURE:0.5}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

logging.file.path=logs
logging.level.root=INFO

internal.secret=${INTERNAL_SECRET:}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
